### ISSUE TITLE
редактирование постов

### ISSUE THREAD

**Issue by nataliaodintsova** [sadsaviour/blog#1]
@sadsaviour 
Я, как Редактор Своих Мыслей, пишу много тескта, делаю ошибки и хочу переформулировать свои излияния, так как я не умею писать идеальный текст с первого раза и буду переживать из-за опечаток(дислексия) и вообще пацаны засмеют.
 Solution: сделать возможность редактирования поста

**Comment by sadsaviour** [comment]
done!
